services:
  - type: web
    name: biometric-backend
    env: node
    plan: free
    branch: main
    rootDir: Backend
    buildCommand: npm install
    startCommand: node --experimental-json-modules src/index.js
    envVars:
      - key: PORT
        value: ${PORT}

      - key: MONGODB_URI
        value: ${MONGODB_URI}

      - key: CORS_ORIGIN
        value: ${CORS_ORIGIN}